"""Add Crop model

Revision ID: 050b9703d471
Revises: e9702f092993
Create Date: 2025-05-17 21:27:13.876718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050b9703d471'
down_revision = 'e9702f092993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('planted_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('health_status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_crop_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_name'))
        batch_op.alter_column('health_status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('planted_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
